# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := common_windows_lib
DEFS_Debug := \
	'-DNO_HEAPCHECKER' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-pthread \
	-fno-exceptions \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-frtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := \
	-I. \
	-I$(VSInstallDir)/DIA SDK/include

DEFS_Release := \
	'-DNO_HEAPCHECKER' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DOFFICIAL_BUILD'

# Flags passed to all source files.
CFLAGS_Release := \
	-pthread \
	-fno-exceptions \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-frtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := \
	-I. \
	-I$(VSInstallDir)/DIA SDK/include

OBJS := \
	$(obj).target/$(TARGET)/common/windows/dia_util.o \
	$(obj).target/$(TARGET)/common/windows/guid_string.o \
	$(obj).target/$(TARGET)/common/windows/http_upload.o \
	$(obj).target/$(TARGET)/common/windows/omap.o \
	$(obj).target/$(TARGET)/common/windows/pdb_source_line_writer.o \
	$(obj).target/$(TARGET)/common/windows/string_utils.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/common/windows/dia_sdk.stamp

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-Wl,-z,noexecstack \
	-rdynamic

LDFLAGS_Release := \
	-pthread \
	-Wl,-z,noexecstack \
	-Wl,--gc-sections

LIBS :=

$(obj).target/common/windows/libcommon_windows_lib.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/common/windows/libcommon_windows_lib.a: LIBS := $(LIBS)
$(obj).target/common/windows/libcommon_windows_lib.a: TOOLSET := $(TOOLSET)
$(obj).target/common/windows/libcommon_windows_lib.a: $(OBJS) FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/common/windows/libcommon_windows_lib.a
# Add target alias
.PHONY: common_windows_lib
common_windows_lib: $(obj).target/common/windows/libcommon_windows_lib.a

# Add target alias to "all" target.
.PHONY: all
all: common_windows_lib

