######################################################################
# Automatically generated by qmake (3.1) Mon Apr 17 15:09:43 2017
######################################################################

TEMPLATE = app
QT += widgets core gui
include(qt-breakpad/qt-breakpad.pri)
TARGET = test_breakpad
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += C++11

# Input
SOURCES += main.cpp
