# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := crash_generation_app
DEFS_Debug := \
	'-DNO_HEAPCHECKER' \
	'-D_DEBUG'

# Flags passed to all source files.
CFLAGS_Debug := \
	-pthread \
	-fno-exceptions \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O0 \
	-g

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-frtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Debug := \
	-I.

DEFS_Release := \
	'-DNO_HEAPCHECKER' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DOFFICIAL_BUILD'

# Flags passed to all source files.
CFLAGS_Release := \
	-pthread \
	-fno-exceptions \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-D_FILE_OFFSET_BITS=64 \
	-fvisibility=hidden \
	-fno-strict-aliasing \
	-O2 \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-frtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden

INCS_Release := \
	-I.

OBJS := \
	$(obj).target/$(TARGET)/client/windows/tests/crash_generation_app/abstract_class.o \
	$(obj).target/$(TARGET)/client/windows/tests/crash_generation_app/crash_generation_app.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(obj).target/client/windows/libcommon.a $(obj).target/client/windows/crash_generation/libcrash_generation_server.a $(obj).target/client/windows/crash_generation/libcrash_generation_client.a $(obj).target/client/windows/handler/libexception_handler.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.cc FORCE_DO_CMD
	@$(call do_cmd,cxx,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-Wl,-z,noexecstack \
	-rdynamic

LDFLAGS_Release := \
	-pthread \
	-Wl,-z,noexecstack \
	-Wl,--gc-sections

LIBS := \
	user32.lib

$(builddir)/crash_generation_app: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(builddir)/crash_generation_app: LIBS := $(LIBS)
$(builddir)/crash_generation_app: LD_INPUTS := $(OBJS) $(obj).target/client/windows/libcommon.a $(obj).target/client/windows/crash_generation/libcrash_generation_server.a $(obj).target/client/windows/crash_generation/libcrash_generation_client.a $(obj).target/client/windows/handler/libexception_handler.a
$(builddir)/crash_generation_app: TOOLSET := $(TOOLSET)
$(builddir)/crash_generation_app: $(OBJS) $(obj).target/client/windows/libcommon.a $(obj).target/client/windows/crash_generation/libcrash_generation_server.a $(obj).target/client/windows/crash_generation/libcrash_generation_client.a $(obj).target/client/windows/handler/libexception_handler.a FORCE_DO_CMD
	$(call do_cmd,link)

all_deps += $(builddir)/crash_generation_app
# Add target alias
.PHONY: crash_generation_app
crash_generation_app: $(builddir)/crash_generation_app

# Add executable to "all" target.
.PHONY: all
all: $(builddir)/crash_generation_app

